### ISSUE TITLE
publish latest version to maven central/jcenter

### ISSUE THREAD

**Issue by vboulaye** [ThinkingLogic/kotlin-builder-annotation#13]
Hi,

First, thanks for this: I am starting looking at introducing kotlin in a legacy java project, and I believe this could greatly help interop with java.

I noticed and the latest versions 1.2.1 is not available neither in maven central nor in jcenter.
Would it be possible to publish it?

**Comment by YetAnotherMatt** [comment]
HI @vboulaye ,

My apologies - I thought I had published the latest version! It should not be available in jcenter and syncing to maven central.

https://bintray.com/bintray/jcenter?filterByPkgName=kotlin-builder

**Comment by vboulaye** [comment]
I can get it now, thanks!
