### ISSUE TITLE
Compilation of generated builder fails if class has a property named "value"

### ISSUE THREAD

**Issue by jxerome** [ThinkingLogic/kotlin-builder-annotation#6]
When the Kotlin object has a property with name "value", the generated builder doesn't compile.

Example:
I have the class:
```kotlin
import com.thinkinglogic.builder.annotation.Builder

@Builder
data class Property(val label: String, var value: String?)
```

In the generated PropertyBuilder the setter for value is:
```kotlin
  fun value(value: String?): PropertyBuilder = apply { value = value }
```
which doesn't compile:
```
e: /.../PropertyBuilder.kt: (17, 56): Val cannot be reassigned
```

**Comment by YetAnotherMatt** [comment]
Hi @jxerome sorry for the delayed response! It seems I had notifications disabled :(
Thanks for the PR - it's been merged now.
